---
apiVersion: v1
kind: Pod
metadata:
  name: lni-sample-kernel-networking
  annotations:
    k8s.v1.cni.cncf.io/networks: lni-ipvlan-whereabouts
spec:
  containers:
  - name: ubuntu
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: ubuntu:latest
    lifecycle:
      postStart:
        exec:
          command:
            [
              "/bin/sh",
              "-c",
              "apt update -y; apt install -y net-tools iputils-ping arping curl",
            ]

---
apiVersion: v1
kind: Pod
metadata:
  name: lni-al2023-nodhcp
  annotations:
    k8s.v1.cni.cncf.io/networks: lni-ipvlan-whereabouts
spec:
  containers:
  - name: lni-al2023-nodhcp
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: public.ecr.aws/amazonlinux/amazonlinux:2023
    lifecycle:
      postStart:
        exec:
          command:
            [
              "/bin/sh",
              "-c",
              "dnf install -y iproute iputils",
            ]
