# Have not found a good way to parameterize values with the config blocks
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lni-ipvlan-whereabouts
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lni-ipvlan-whereabouts",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "eth1",
          "mode": "l2",
          "ipam": {
            "type": "whereabouts",
            "range": "192.168.2.168/29",
            "exclude": [
              "192.168.2.169/32"  
            ]
          }
        }
      ]
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lni-ipvlan-dhcp
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lni-ipvlan-dhcp",
      "type": "ipvlan",
      "mode": "l2",
      "master": "eth1",
      "ipam": {
        "type": "dhcp"
      }
    }'
