---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lni-ipvlan-1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lni-ipvlan-1",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "eth1",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "addresses": [
               {
                 "address": "192.168.2.170/22",
                 "gateway": "192.168.1.1"
               }
            ],
            "routes": [
              { "dst": "192.168.0.0/22" }
            ]
          }
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lni-ipvlan-2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lni-ipvlan-2",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "eth1",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "addresses": [
               {
                 "address": "192.168.2.171/22",
                 "gateway": "192.168.1.1"
               }
            ],
            "routes": [
              { "dst": "192.168.0.0/22" }
            ]
          }
        }
      ]
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lni-ipvlan-3
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lni-ipvlan-3",
      "type": "ipvlan",
      "mode": "l2",
      "master": "eth1",
      "ipam": {
        "type": "dhcp"
      }
    }'


---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lni-ipvlan-4
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lni-ipvlan-4",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "eth1",
          "mode": "l3",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.0.0/22",
            "rangeStart": "192.168.2.172",
            "rangeEnd": "192.168.2.174",
            "routes": [
              { "dst": "192.168.0.0/22" }
            ],
            "gateway": "192.168.1.1"
          }
        }
      ]
    }'



---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lni-ipvlan-5
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lni-ipvlan-5",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "eth1",
          "mode": "l2",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.0.0/22",
            "rangeStart": "192.168.2.175",
            "rangeEnd": "192.168.2.177",
            "routes": [
              { "dst": "192.168.0.0/22" }
            ],
            "gateway": "192.168.1.1"
          }
        }
      ]
    }'


